on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Download Libraries
      run: scripts/download_libraries.sh
    - name: Compile
      run: javac -cp "lib/*" src/WebSocketServer.java
